"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation"; import { z } from "zod";
import { requireAdminArea } from "@/lib/admin"; import { audit } from "@/lib/audit"; import { prisma } from "@/lib/prisma";
const providerSchema=z.object({code:z.string().trim().regex(/^[A-Z0-9_-]{2,50}$/),name:z.string().trim().min(2).max(100),isActive:z.boolean()}); const mapSchema=z.object({providerId:z.string().cuid(),productId:z.string().cuid(),externalSku:z.string().trim().min(1).max(100),isActive:z.boolean()});
function done(message:string){revalidatePath("/admin/providers");redirect(`/admin/providers?message=${encodeURIComponent(message)}`)}
export async function createProvider(form:FormData){const a=await requireAdminArea("catalog");const d=providerSchema.parse({...Object.fromEntries(form),isActive:form.get("isActive")==="on"});const p=await prisma.provider.create({data:d});await audit(a.id,"CREATE","Provider",p.id,d);done("Provider ditambahkan.")}
export async function updateProvider(form:FormData){const a=await requireAdminArea("catalog");const id=z.string().cuid().parse(form.get("id"));const d=providerSchema.parse({...Object.fromEntries(form),isActive:form.get("isActive")==="on"});await prisma.provider.update({where:{id},data:d});await audit(a.id,"UPDATE","Provider",id,d);done("Provider diperbarui.")}
export async function deleteProvider(form:FormData){const a=await requireAdminArea("catalog");const id=z.string().cuid().parse(form.get("id"));const p=await prisma.provider.findUnique({where:{id},include:{_count:{select:{products:true}}}});if(!p)throw new Error("Provider tidak ditemukan.");if(p._count.products)throw new Error("Hapus mapping produk provider terlebih dahulu.");await prisma.provider.delete({where:{id}});await audit(a.id,"DELETE","Provider",id,{name:p.name});done("Provider dihapus.")}
export async function createMapping(form:FormData){const a=await requireAdminArea("catalog");const d=mapSchema.parse({...Object.fromEntries(form),isActive:form.get("isActive")==="on"});const x=await prisma.providerProduct.create({data:d});await audit(a.id,"CREATE","ProviderProduct",x.id,d);done("Mapping produk dibuat.")}
export async function deleteMapping(form:FormData){const a=await requireAdminArea("catalog");const id=z.string().cuid().parse(form.get("id"));await prisma.providerProduct.delete({where:{id}});await audit(a.id,"DELETE","ProviderProduct",id);done("Mapping dihapus.")}
