"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireAdminArea } from "@/lib/admin";
import { audit } from "@/lib/audit";
import { decimal, moneySchema } from "@/lib/money";
import { prisma } from "@/lib/prisma";
import { deleteProductImage, saveProductImage } from "@/lib/product-image";
const schema = z.object({ gameId: z.string().cuid(), name: z.string().trim().min(2).max(120), sku: z.string().trim().min(2).max(100), providerPrice: moneySchema, sellingPrice: moneySchema, isActive: z.boolean() });
function data(form: FormData) { const x = schema.parse({ ...Object.fromEntries(form), isActive: form.get("isActive") === "on" }); return { ...x, providerPrice: decimal(x.providerPrice), sellingPrice: decimal(x.sellingPrice) }; }
function done(message: string) { revalidatePath("/admin/products"); revalidatePath("/admin"); revalidatePath("/"); revalidatePath("/games"); redirect(`/admin/products?message=${encodeURIComponent(message)}`); }
async function getNewImage(form: FormData) { const file = form.get("image"); return file instanceof File && file.size > 0 ? saveProductImage(file) : null; }
export async function createProduct(form: FormData) { const actor = await requireAdminArea("catalog"); const value = data(form); const image = await getNewImage(form); let persisted = false; try { const product = await prisma.gameProduct.create({ data: { ...value, image } }); persisted = true; await audit(actor.id, "CREATE", "GameProduct", product.id, { ...value, image, providerPrice: value.providerPrice.toString(), sellingPrice: value.sellingPrice.toString() }); done("Produk ditambahkan."); } catch (error) { if (!persisted) await deleteProductImage(image); throw error; } }
export async function updateProduct(form: FormData) { const actor = await requireAdminArea("catalog"); const id = z.string().cuid().parse(form.get("id")); const existing = await prisma.gameProduct.findUnique({ where: { id }, select: { image: true } }); if (!existing) throw new Error("Produk tidak ditemukan."); const value = data(form); const newImage = await getNewImage(form); const image = newImage ?? (form.get("removeImage") === "on" ? null : existing.image); let persisted = false; try { const product = await prisma.gameProduct.update({ where: { id }, data: { ...value, image } }); persisted = true; if (newImage && existing.image) await deleteProductImage(existing.image); if (!image && existing.image) await deleteProductImage(existing.image); await audit(actor.id, "UPDATE", "GameProduct", id, { ...value, image, providerPrice: value.providerPrice.toString(), sellingPrice: value.sellingPrice.toString() }); done(`Produk ${product.name} diperbarui.`); } catch (error) { if (!persisted) await deleteProductImage(newImage); throw error; } }
export async function deleteProduct(form: FormData) { const actor = await requireAdminArea("catalog"); const id = z.string().cuid().parse(form.get("id")); const product = await prisma.gameProduct.findUnique({ where: { id }, include: { _count: { select: { orderItems: true, providerProducts: true } } } }); if (!product) throw new Error("Produk tidak ditemukan."); if (product._count.orderItems || product._count.providerProducts) throw new Error("Produk yang telah dipakai pesanan/provider tidak dapat dihapus."); await prisma.gameProduct.delete({ where: { id } }); await deleteProductImage(product.image); await audit(actor.id, "DELETE", "GameProduct", id, { name: product.name }); done("Produk dihapus."); }
